CedFCIC/Controllers/ComprobanteController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using CedFCIC.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using NPOI.XSSF.UserModel;
using NPOI.SS.UserModel;

namespace CedFCIC.Controllers
{
    public class ComprobanteController : FCICController
    {
        private readonly reCAPTCHAService _ReCAPTCHAService;
        private readonly RequestHandler _RequestHandler;
        private readonly IWebHostEnvironment _env;

        public ComprobanteController(IConfiguration configuracion, RequestHandler requestHandler, reCAPTCHAService _reCAPTCHAService, IWebHostEnvironment env) : base(configuracion, requestHandler)
        {
            _ReCAPTCHAService = _reCAPTCHAService;
            _RequestHandler = requestHandler;
            _env = env;
        }

        // GET: Articulos
        public async Task<IActionResult> Index()
        {
            List<CedFCIC.Entidades.Comprobante> listaComprobantes = new List<CedFCIC.Entidades.Comprobante>();
            CedFCIC.Models.PagedResult<CedFCIC.Entidades.Comprobante, CedFCIC.Models.ComprobanteFiltro> PagedResult = new CedFCIC.Models.PagedResult<CedFCIC.Entidades.Comprobante, CedFCIC.Models.ComprobanteFiltro>();
            try
            {
                Entidades.Sesion sesion = HttpContext.Session.GetObj<Entidades.Sesion>("Sesion");
                if (Funciones.SessionOK(sesion))
                {
                    if (HttpContext.Request.Query["page"].ToString() != "")
                    {
                        int cantidadFilas = 0;
                        PagedResult.PageSize = sesion.Usuario.CantidadFilasXPagina;
                        PagedResult.CurrentPage = Convert.ToInt32(HttpContext.Request.Query["page"].ToString());
                        List<CedFCIC.Entidades.Estado> estadosVentas = new List<CedFCIC.Entidades.Estado>();
                        List<CedFCIC.Entidades.Estado> estadosCompras = new List<CedFCIC.Entidades.Estado>();
                        List<FeaEntidades.TiposDeComprobantes.TipoComprobante> tiposComprobantes = new List<FeaEntidades.TiposDeComprobantes.TipoComprobante>();
                        CedFCIC.Entidades.Persona persona = new CedFCIC.Entidades.Persona();
                        CedFCIC.Entidades.NaturalezaComprobante naturalezaComprobante = new CedFCIC.Entidades.NaturalezaComprobante();
                        naturalezaComprobante.Id = "Venta";
                        naturalezaComprobante.Descr = "Venta";
                        PagedResult.Filtro = JsonConvert.DeserializeObject<ComprobanteFiltro>(TempData["ComprobanteFiltro"].ToString());
                        string fecDsd = Convert.ToDateTime(PagedResult.Filtro.FiltroFechaDesde).ToString("yyyyMMdd");
                        string fecHst = Convert.ToDateTime(PagedResult.Filtro.FiltroFechaHasta).ToString("yyyyMMdd");
                        if (PagedResult.Filtro.FiltroRazonSocial != null)
                        { 
                            persona.RazonSocial = PagedResult.Filtro.FiltroRazonSocial;
                        }
                        listaComprobantes = RN.Comprobante.ListaFiltradaPagging(out cantidadFilas, PagedResult.CurrentPage, "", estadosVentas, estadosCompras, tiposComprobantes, fecDsd, fecHst, persona, naturalezaComprobante, "", "", "", sesion);
                        PagedResult.Lista = listaComprobantes;
                        PagedResult.RowCount = ViewBag.CantidadFilas = cantidadFilas;
                        if (listaComprobantes.Count > 0)
                        {
                            ViewBag.Boton1ReadOnly = "";
                        }
                        else 
                        {
                            ViewBag.Boton1ReadOnly = "Disabled";
                        }
                    }
                    else
                    {
                        if (PagedResult.Filtro == null)
                        {
                            PagedResult.Filtro = new ComprobanteFiltro();
                        }
                        PagedResult.Filtro.FiltroFechaDesde = Convert.ToDateTime(DateTime.Now).ToString("01/MM/yyyy");
                        PagedResult.Filtro.FiltroFechaHasta = Convert.ToDateTime(DateTime.Now).ToString("dd/MM/yyyy");
                        PagedResult.Filtro.FiltroRazonSocial = "";
                        ViewBag.Boton1ReadOnly = "Disabled";
                    }
                    _RequestHandler.HandleAboutRequest();
                    sesion = HttpContext.Session.GetObj<Entidades.Sesion>("Sesion");
                }
                else
                {
                    TempData["Ex"] = "Sesion finalizada por timeout.";
                    return RedirectToAction("Ingresar", "Usuario");
                }
            }
            catch (Exception ex)
            {
                if (ex.InnerException == null)
                {
                    ViewData["Ex"] = ex.Message;
                }
                else
                {
                    ViewData["Ex"] = string.Format("{0}({1})", ex.Message, ex.InnerException.Message);
                }
            }
            TempData.Keep();
            return View(PagedResult);
        }
        [HttpPost]
        //public async Task<IActionResult> Index([FromForm] string FiltroRazonSocial, [Bind("FiltroFechaDesde, FiltroFechaHasta, FiltroRazonSocial")] CedFCIC.Models.ComprobanteFiltro comprobanteFiltro)
        public async Task<IActionResult> Index([Bind("FiltroFechaDesde, FiltroFechaHasta, FiltroRazonSocial")] CedFCIC.Models.ComprobanteFiltro comprobanteFiltro)
        {
            List<CedFCIC.Entidades.Comprobante> listaComprobantes = new List<CedFCIC.Entidades.Comprobante>();
            CedFCIC.Models.PagedResult<CedFCIC.Entidades.Comprobante, CedFCIC.Models.ComprobanteFiltro> PagedResult = new CedFCIC.Models.PagedResult<CedFCIC.Entidades.Comprobante, CedFCIC.Models.ComprobanteFiltro>();
            try
            {
                Entidades.Sesion sesion = HttpContext.Session.GetObj<Entidades.Sesion>("Sesion");
                if (Funciones.SessionOK(sesion))
                {
                    if (ModelState.IsValid)
                    {
                        int cantidadFilas = 0;
                        _RequestHandler.HandleAboutRequest();
                        sesion = HttpContext.Session.GetObj<Entidades.Sesion>("Sesion");
                        List<CedFCIC.Entidades.Estado> estadosVentas = new List<CedFCIC.Entidades.Estado>();
                        List<CedFCIC.Entidades.Estado> estadosCompras = new List<CedFCIC.Entidades.Estado>();
                        List<FeaEntidades.TiposDeComprobantes.TipoComprobante> tiposComprobantes = new List<FeaEntidades.TiposDeComprobantes.TipoComprobante>();
                        CedFCIC.Entidades.Persona persona = new CedFCIC.Entidades.Persona();
                        CedFCIC.Entidades.NaturalezaComprobante naturalezaComprobante = new CedFCIC.Entidades.NaturalezaComprobante();
                        naturalezaComprobante.Id = "Venta";
                        naturalezaComprobante.Descr = "Venta";
                        string fecDsd = Convert.ToDateTime(comprobanteFiltro.FiltroFechaDesde).ToString("yyyyMMdd");
                        string fecHst = Convert.ToDateTime(comprobanteFiltro.FiltroFechaHasta).ToString("yyyyMMdd");
                        if (comprobanteFiltro.FiltroRazonSocial != null)
                        {
                            persona.RazonSocial = comprobanteFiltro.FiltroRazonSocial;
                        }
                        listaComprobantes = RN.Comprobante.ListaFiltradaPagging(out cantidadFilas, 1, "", estadosVentas, estadosCompras, tiposComprobantes, fecDsd, fecHst, persona, naturalezaComprobante, "", "", "", sesion);
                        PagedResult.Lista = listaComprobantes;
                        PagedResult.Filtro = comprobanteFiltro;
                        PagedResult.PageSize = sesion.Usuario.CantidadFilasXPagina;
                        PagedResult.CurrentPage = 1;
                        PagedResult.RowCount = ViewBag.CantidadFilas = cantidadFilas;
                        if (listaComprobantes.Count > 0)
                        {
                            ViewBag.Boton1ReadOnly = "";
                        }
                        else
                        {
                            ViewBag.Boton1ReadOnly = "Disabled";
                        }
                    }
                }
                else
                {
                    TempData["Ex"] = "Sesion finalizada por timeout.";
                    return RedirectToAction("Ingresar", "Usuario");
                }
            }
            catch (Exception ex)
            {
                if (ex.InnerException == null)
                {
                    ViewData["Ex"] = ex.Message;
                }
                else
                {
                    ViewData["Ex"] = string.Format("{0}({1})", ex.Message, ex.InnerException.Message);
                }
            }
            TempData["ComprobanteFiltro"] = JsonConvert.SerializeObject(comprobanteFiltro);
            TempData.Keep();
            return View(PagedResult);
        }
        [HttpPost]
        public async Task<IActionResult> ExportarAExcel()
        {
            if (TempData["ComprobanteFiltro"] != null)
            { 
                string webRootPath = _env.WebRootPath;
                string fileName = @"Testingdummy.xlsx";
                string URL = string.Format("{0}://{1}/{2}", Request.Scheme, Request.Host, fileName);
                FileInfo file = new FileInfo(Path.Combine(webRootPath, fileName));
                var memoryStream = new MemoryStream();

CedFCIC/Views/Comprobante/Index.cshtml
@model PagedResult<CedFCIC.Entidades.Comprobante, CedFCIC.Models.ComprobanteFiltro>
@{
    ViewData["Title"] = "Consulta de Comprobantes";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>
<form asp-action="Index" method="post" autocomplete="off">
    <div class="container">
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="col-md-2 col-sm-2">
                <label asp-for="Filtro.FiltroFechaDesde" class="control-label"></label>
                <input asp-for="Filtro.FiltroFechaDesde" id="FiltroFechaDesde" name="FiltroFechaDesde" class="form-control" style="width:110px" lang="es-ar" type="text" value="@Model.Filtro.FiltroFechaDesde" />
                <span asp-validation-for="Filtro.FiltroFechaDesde" class="text-danger"></span>
            </div>
            <div class="col-md-2 col-sm-2">
                <label asp-for="Filtro.FiltroFechaHasta" class="control-label"></label>
                <input asp-for="Filtro.FiltroFechaHasta" id="FiltroFechaHasta" name="FiltroFechaHasta" class="form-control" style="width:110px" lang="es-ar" type="text" value="@Model.Filtro.FiltroFechaHasta" />
                <span asp-validation-for="Filtro.FiltroFechaHasta" class="text-danger"></span>
                @*<label class="control-label">Fecha Hasta</label>
                    <input type="text" name="FiltroFechaHasta" id="FiltroFechaHasta" class="form-control" style="width:100px">*@
            </div>
            <div class="form-group col-md-8 col-sm-8">
                <label asp-for="Filtro.FiltroRazonSocial" class="control-label"></label>
                <input asp-for="Filtro.FiltroRazonSocial" id="FiltroFechaHasta" name="FiltroRazonSocial" class="form-control" value="@Model.Filtro.FiltroRazonSocial" />
                <span asp-validation-for="Filtro.FiltroRazonSocial" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12">
                <input type="submit" value="Aceptar" class="btn btn-outline-primary" />
                <a asp-action="Index" asp-controller="Comprobante" class="btn btn-outline-primary">Volver</a>
            </div>
            <div class="form-group col-md-12 col-sm-12">
                <a asp-action="Crear">Crear nuevo comprobante</a>
            </div>
            @if (Model.Lista.Count > 0)
            {
                <div class="col-md-12 col-sm-12">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Lista[0].Cuit)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Lista[0].TipoComprobante.Descr)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Lista[0].NroPuntoVta)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Lista[0].Nro)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Lista[0].RazonSocial)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Lista[0].Moneda)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Lista[0].Importe)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Lista[0].Estado)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Lista)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Cuit)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TipoComprobante.Descr)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.NroPuntoVta)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Nro)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.RazonSocial)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Moneda)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Importe)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Estado)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Modificar", "Modificar", new { Cuit = item.Cuit, Nro = item.Nro }) |
                                        @Html.ActionLink("Detalle", "Detalle", new { Cuit = item.Cuit, Id = item.Nro })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="form-group col-md-12 col-sm-12">
                    @(await Component.InvokeAsync<CedFCIC.ViewComponents.PagerViewComponent>(Model))
                </div>
            }
        </div>
    </div>
</form>
<form asp-action="ExportarAExcel" method="post" enctype="multipart/form-data">
    <div class="container">
        <div class="row">
            <div class="col-md-12" style="padding-top:10px;">
                <button type="submit" class="btn btn-outline-primary" @ViewBag.Boton1ReadOnly>Exportar a Excel</button>
            </div>
        </div>
        <div id="divData"></div>
    </div>
</form>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(function () {
            var options = $.extend({}, // empty object
                $.datepicker.regional["es"], {
                dateFormat: "dd/mm/yy"
            } // your custom options
            );
            $("#FiltroFechaDesde").datepicker(options);
        });
    </script>
    <script>
        $(function () {
            var options = $.extend({}, // empty object
                $.datepicker.regional["es"], {
                dateFormat: "dd/mm/yy"
            } // your custom options
            );
            $("#FiltroFechaHasta").datepicker(options);
        });
    </script>
}