CedFCIC/Controllers/ArticuloController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using CedFCIC.Models;
using CedFCIC.Entidades;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;

namespace CedFCIC.Controllers
{
    public class ArticuloController : FCICController
    {
        private readonly reCAPTCHAService _ReCAPTCHAService;
        //private readonly RequestHandler _RequestHandler;

        public ArticuloController(IConfiguration configuracion, RequestHandler requesthandler, reCAPTCHAService _reCAPTCHAService) : base(configuracion, requesthandler)
        {
            _ReCAPTCHAService = _reCAPTCHAService;
            //_RequestHandler = requestHandler;
        }

        // GET: Articulos
        public async Task<IActionResult> Index()
        {
            List<CedFCIC.Entidades.Articulo> listaArticulos = new List<CedFCIC.Entidades.Articulo>();
            Entidades.Sesion sesion = HttpContext.Session.GetObj<Entidades.Sesion>("Sesion");
            if (Funciones.SessionOK(sesion))
            {
                _RequestHandler.HandleAboutRequest();
                sesion = HttpContext.Session.GetObj<Entidades.Sesion>("Sesion");
                listaArticulos = RN.Articulo.ListaPorCuit(false, false, sesion);
            }
            else
            {
                TempData["Ex"] = "Sesion finalizada por timeout.";
                return RedirectToAction("Ingresar", "Usuario");
            }
            return View(listaArticulos);
        }

        [HttpGet]
        public IActionResult Crear()
        {
            CedFCIC.Entidades.Articulo articulo = new CedFCIC.Entidades.Articulo();
            Entidades.Sesion sesion = HttpContext.Session.GetObj<Entidades.Sesion>("Sesion");
            if (Funciones.SessionOK(sesion))
            {
                _RequestHandler.HandleAboutRequest();
                sesion = HttpContext.Session.GetObj<Entidades.Sesion>("Sesion");
                ViewData["Message"] = "";
                articulo.Cuit = sesion.Cuit.Nro;
                CompletarComboEstado("Vigente");
                CompletarComboUnidad("7");
                CompletarComboIndicacionExentoGravado("G");
            }
            else
            {
                TempData["Ex"] = "Sesion finalizada por timeout.";
                return RedirectToAction("Ingresar", "Usuario");
            }
            return View(articulo);
        }

        [HttpPost]
        public IActionResult Crear([Bind("Cuit,Id,Descr,UnidadId,IndicacionExentoGravadoId,AlicuotaIVA,Stock,EstadoId")] CedFCIC.Entidades.Articulo articulo)
        {
            try
            {
                Entidades.Sesion sesion = HttpContext.Session.GetObj<Entidades.Sesion>("Sesion");
                if (Funciones.SessionOK(sesion))
                {
                    if (ModelState.IsValid)
                    {
                        RN.Articulo.Crear(articulo, sesion);
                        string resp = "Artículo creado satisfactoriamente.";
                        ViewData["TextoMensaje"] = resp;

                    }
                    else
                    {
                        ViewData["Ex"] = "Ingrese los datos requeridos";
                    }
                }
                else
                {
                    TempData["Ex"] = "Sesion finalizada por timeout.";
                    return RedirectToAction("Ingresar", "Usuario");
                }
            }
            catch (Exception ex)
            {
                ViewData["Ex"] = ex.Message;
            }
            CompletarComboEstado(articulo.EstadoId);
            CompletarComboUnidad(articulo.UnidadId);
            CompletarComboIndicacionExentoGravado(articulo.IndicacionExentoGravadoId);
            return View(articulo);
        }
        private void CompletarComboEstado(string valor)
        {
            List<CedFCIC.Entidades.Estado> estadoLista = new List<CedFCIC.Entidades.Estado>();
            estadoLista.Add(new Estado("Vigente", "Vigente", true));
            ViewData["EstadoId"] = new SelectList(estadoLista, "Id", "Descr", valor);
            //List<SelectListItem> litems = new List<SelectListItem>();
            //SelectListItem item = new SelectListItem("Vigente", "V", true, false);
            //litems.Add(item);
            //ViewData["EstadoId"] = new SelectList(litems, "Value", "Text", valor);
        }
        private void CompletarComboUnidad(string valor)
        {
            List<FeaEntidades.CodigosUnidad.CodigoUnidad> unidadLista = new List<FeaEntidades.CodigosUnidad.CodigoUnidad>();
            unidadLista = FeaEntidades.CodigosUnidad.CodigoUnidad.Lista();
            ViewData["UnidadId"] = new SelectList(unidadLista, "Codigo", "Descr", valor);
        }
        private void CompletarComboIndicacionExentoGravado(string valor)
        {
            List<FeaEntidades.CodigosOperacion.CodigoOperacion> codopeLista = new List<FeaEntidades.CodigosOperacion.CodigoOperacion>();
            codopeLista = FeaEntidades.CodigosOperacion.CodigoOperacion.ListaDetalle();
            ViewData["IndicacionExentoGravadoId"] = new SelectList(codopeLista, "Codigo", "Descr", valor);
        }

        public async Task<IActionResult> Detalle(string cuit, string id)
        {
            if (cuit == null || id == null)
            {
                return NotFound();
            }
            Entidades.Sesion sesion = HttpContext.Session.GetObj<Entidades.Sesion>("Sesion");
            CedFCIC.Entidades.Articulo articulo = new CedFCIC.Entidades.Articulo();
            if (Funciones.SessionOK(sesion))
            {
                _RequestHandler.HandleAboutRequest();
                sesion = HttpContext.Session.GetObj<Entidades.Sesion>("Sesion");
                articulo = RN.Articulo.Leer(cuit, id, true, sesion);
                ViewData["Message"] = "";
                //CompletarComboEstado(articulo.Estado);
                //CompletarComboUnidad(articulo.Unidad.Id);
                //CompletarComboIndicacionExentoGravado(articulo.IndicacionExentoGravado);
            }
            else
            {
                TempData["Ex"] = "Sesion finalizada por timeout.";
                return RedirectToAction("Ingresar", "Usuario");
            }
            return View(articulo);
        }
        [HttpGet]
        public IActionResult Modificar(string cuit, string id)
        {
            if (cuit == null || id == null)
            {
                TempData["Ex"] = "Problemas para obtener la identificación del artículo";
            }
            Entidades.Sesion sesion = HttpContext.Session.GetObj<Entidades.Sesion>("Sesion");
            CedFCIC.Entidades.Articulo articulo = new CedFCIC.Entidades.Articulo();
            if (Funciones.SessionOK(sesion))
            {
                _RequestHandler.HandleAboutRequest();
                sesion = HttpContext.Session.GetObj<Entidades.Sesion>("Sesion");
                articulo = RN.Articulo.Leer(cuit, id, true, sesion);
                ViewData["WFId"] = articulo.WFId;
                ViewData["Message"] = "";
                CompletarComboEstado(articulo.Estado);
                CompletarComboUnidad(articulo.Unidad.Id);
                CompletarComboIndicacionExentoGravado(articulo.IndicacionExentoGravado);
            }
            else
            {
                TempData["Ex"] = "Sesion finalizada por timeout.";
                return RedirectToAction("Ingresar", "Usuario");
            }
            return View(articulo);
        }

        [HttpPost]
        public IActionResult Modificar([Bind("Cuit,Id,Descr,UnidadId,IndicacionExentoGravadoId,AlicuotaIVA,Stock,EstadoId,WF.Id")] CedFCIC.Entidades.Articulo articulo)
        {
            try
            {
                Entidades.Sesion sesion = HttpContext.Session.GetObj<Entidades.Sesion>("Sesion");
                if (Funciones.SessionOK(sesion))
                {
                    if (ModelState.IsValid)
                    {
                        List<FeaEntidades.CodigosUnidad.CodigoUnidad> listaCU = FeaEntidades.CodigosUnidad.CodigoUnidad.Lista();
                        FeaEntidades.CodigosUnidad.CodigoUnidad CU = listaCU.Find(element => element.Codigo.Equals(Convert.ToInt16(articulo.UnidadId)));
                        articulo.Unidad.Descr = CU.Descr;
                        RN.Articulo.Modificar(articulo, articulo, sesion);
                        string resp = "Artículo modificado satisfactoriamente.";
                        ViewData["TextoMensaje"] = resp;
                    }
                    else
                    {
                        ViewData["Ex"] = "Ingrese los datos requeridos";
                    }
                }
                else
                {
                    TempData["Ex"] = "Sesion finalizada por timeout.";
                    return RedirectToAction("Ingresar", "Usuario");
                }
            }
            catch (Exception ex)
            {
                ViewData["Ex"] = ex.Message;
            }
            CompletarComboEstado(articulo.EstadoId);
            CompletarComboUnidad(articulo.UnidadId);
            CompletarComboIndicacionExentoGravado(articulo.IndicacionExentoGravadoId);
            return View(articulo);
        }

        [HttpGet]
        public IActionResult Baja(string cuit, string id)
        {
            if (cuit == null || id == null)
            {
                TempData["Ex"] = "Problemas para obtener la identificación del artículo";
            }
            Entidades.Sesion sesion = HttpContext.Session.GetObj<Entidades.Sesion>("Sesion");
            CedFCIC.Entidades.Articulo articulo = new CedFCIC.Entidades.Articulo();
            if (Funciones.SessionOK(sesion))
            {
                _RequestHandler.HandleAboutRequest();

CedFCIC/Controllers/FacturaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace CedFCIC.Controllers
{
    public class FacturaController : Controller
    {
        public IActionResult Index()
        {
            Entidades.Sesion sesion = HttpContext.Session.GetObj<Entidades.Sesion>("Sesion");
            if (Funciones.SessionOK(sesion))
            {
                ViewData["Usuario"] = sesion.Usuario;
            }
            else
            {
                TempData["Ex"] = "Sesion finalizada por timeout.";
                return RedirectToAction("Ingresar", "Usuario");
            }
            return View();
        }
        public IActionResult PaginaAyudaInstOFE001()
        {
            Entidades.Sesion sesion = HttpContext.Session.GetObj<Entidades.Sesion>("Sesion");
            if (Funciones.SessionOK(sesion))
            {
                ViewData["Usuario"] = sesion.Usuario;
            }
            else
            {
                TempData["Ex"] = "Sesion finalizada por timeout.";
                return RedirectToAction("Ingresar", "Usuario");
            }
            return View("Ayuda/Instructivas/OperarFacturaElectronica001");
        }
    }
}

CedFCIC/Views/Articulo/Baja.cshtml
@model CedFCIC.Entidades.Articulo;
@{
    ViewData["Title"] = ViewData["AccionDescr"] + " del Artículo";
}

<h2>@ViewData["Title"]</h2><h5> (WF: @ViewBag.WFId)</h5>
<form asp-action="Baja" method="post">
    <div class="container">
        <div class="row">
            <div class="form-group col-md-12">
                <h4></h4>
                <hr />
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Cuit)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Cuit)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Id)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Id)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Descr)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Descr)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.GTIN)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.GTIN)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.IndicacionExentoGravado)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.IndicacionExentoGravado)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.UnidadDescr)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.UnidadDescr)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Estado)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Estado)
                    </dd>
                </dl>
            </div>
            <div class="form-group col-md-12">
                @{
                    if (ViewData["Accion"].ToString() == "Baja")
                    {
                        @Html.ActionLink("Anulación de Baja", "Baja", "Articulo", new { Id = Model.Cuit, Cuit = Model.Id, Accion = "AnulBaja" }, new { @class = "btn btn-outline-primary" });
                    }
                    else
                    {
                        @Html.ActionLink("Baja", "Baja", "Articulo", new { Id = Model.Cuit, Cuit = Model.Id, Accion = "Baja"}, new { @class = "btn btn-outline-primary" });
                    }
                }
                <a asp-action="Index" class="btn btn-outline-primary">Volver</a>
            </div>
        </div>
    </div>
</form>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

CedFCIC/Views/Articulo/Crear.cshtml
@model CedFCIC.Entidades.Articulo;
@{
    ViewData["Title"] = "Crear artículo";
}
@using Microsoft.Extensions.Options

<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>
<form asp-action="Crear">
    <div class="container">
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group col-md-6">
                <label asp-for="Cuit" class="control-label"></label>
                <input asp-for="Cuit" class="form-control" readonly="readonly" />
                <span asp-validation-for="Cuit" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12">
                <label asp-for="Descr" class="control-label"></label>
                <input asp-for="Descr" class="form-control" />
                <span asp-validation-for="Descr" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12">
                <label asp-for="GTIN" class="control-label"></label>
                <input asp-for="GTIN" class="form-control" />
                <span asp-validation-for="GTIN" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12">
                <label asp-for="UnidadId" class="control-label"></label>
                <select asp-for="UnidadId" class="form-control" asp-items="ViewBag.UnidadId"></select>
                <span asp-validation-for="UnidadId" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12">
                <label asp-for="IndicacionExentoGravadoId" class="control-label"></label>
                <select asp-for="IndicacionExentoGravadoId" class="form-control" asp-items="ViewBag.IndicacionExentoGravadoId"></select>
                <span asp-validation-for="IndicacionExentoGravadoId" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12">
                <label asp-for="AlicuotaIVA" class="control-label"></label>
                <input asp-for="AlicuotaIVA" class="form-control" />
                <span asp-validation-for="AlicuotaIVA" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12">
                <label asp-for="EstadoId" class="control-label">Estado</label>
                <select asp-for="EstadoId" class="form-control" asp-items="ViewBag.EstadoId" disabled="disabled"></select>
                <span asp-validation-for="EstadoId" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12">
                <input type="submit" value="Aceptar" class="btn btn-outline-primary" />
                <a asp-action="Index" asp-controller="Factura" class="btn btn-outline-primary">Volver</a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}
@{
    if (@TempData["Msg"] != null)
    {
        <script>
            alert('@TempData["msg"]')
        </script>
    }
}  

CedFCIC/Views/Articulo/Detalle.cshtml
@model CedFCIC.Entidades.Articulo;
@{
    ViewData["Title"] = "Detalle de Artículo";
}

<h2>@ViewData["Title"]</h2>
<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cuit)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cuit)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Descr)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Descr)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GTIN)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GTIN)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IndicacionExentoGravado)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IndicacionExentoGravado)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UnidadDescr)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UnidadDescr)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Modificar", "Modificar", new { Id = Model.Cuit, Cuit = Model.Id }) |
    <a asp-action="Index">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

CedFCIC/Views/Articulo/Index.cshtml
@model IEnumerable<CedFCIC.Entidades.Articulo>

@{
    ViewData["Title"] = "Consulta de Artículos";
    //var me = ViewData["Medio"] as CedFCIC.Entidades.Medio;
}

<h2>@ViewData["Title"]</h2>
<form asp-action="Index" method="post" autocomplete="off">
    <div class="container">
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <!--<div class="col-md-2 col-sm-2">
                <label asp-for="Filtro.FiltroFechaDesde" class="control-label"></label>
                <input asp-for="Filtro.FiltroFechaDesde" id="FiltroFechaDesde" name="FiltroFechaDesde" class="form-control" style="width:110px" lang="es-ar" type="text" value="@TempData["FiltroFechaDesde"]" />
                <span asp-validation-for="Filtro.FiltroFechaDesde" class="text-danger"></span>
            </div>
            <div class="col-md-2 col-sm-2">
                <label asp-for="Filtro.FiltroFechaHasta" class="control-label"></label>
                <input asp-for="Filtro.FiltroFechaHasta" id="FiltroFechaHasta" name="FiltroFechaHasta" class="form-control" style="width:110px" lang="es-ar" type="text" value="@TempData["FiltroFechaHasta"]" />
                <span asp-validation-for="Filtro.FiltroFechaHasta" class="text-danger"></span>
                @*<label class="control-label">Fecha Hasta</label>
                    <input type="text" name="FiltroFechaHasta" id="FiltroFechaHasta" class="form-control" style="width:100px">*@
            </div>
            <div class="form-group col-md-8 col-sm-8">
                <label asp-for="Filtro.FiltroRazonSocial" class="control-label"></label>
                <input asp-for="Filtro.FiltroRazonSocial" id="FiltroFechaHasta" name="FiltroRazonSocial" class="form-control" value="@TempData["FiltroRazonSocial"]" />
                <span asp-validation-for="Filtro.FiltroRazonSocial" class="text-danger"></span>
            </div>-->
            <div class="form-group col-md-12">
                <input type="submit" value="Aceptar" class="btn btn-outline-primary" />
                <a asp-action="Index" asp-controller="Comprobante" class="btn btn-outline-primary">Volver</a>
            </div>

            <p>
                <a asp-action="Crear">Crear nuevo artículo</a>
            </p>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Cuit)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Id)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Descr)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.GTIN)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.UnidadDescr)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.IndicacionExentoGravado)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.AlicuotaIVA)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Estado)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Cuit)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Descr)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.GTIN)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UnidadDescr)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IndicacionExentoGravado)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.AlicuotaIVA)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Estado)
                            </td>
                            <td>
                                @Html.ActionLink("Modificar", "Modificar", "Articulo", new { Cuit = item.Cuit, Id = item.Id }) | 
                                @Html.ActionLink("Baja/Anul", "Baja", "Articulo", new { Cuit = item.Cuit, Id = item.Id }) |
                                @Html.ActionLink("Detalle", "Detalle", "Articulo", new { Cuit = item.Cuit, Id = item.Id })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

CedFCIC/Views/Articulo/Modificar.cshtml
@model CedFCIC.Entidades.Articulo;
@{
    ViewData["Title"] = "Modificar artículo";
}
@using Microsoft.Extensions.Options

<h2>@ViewData["Title"]</h2><h5> (WF: @ViewBag.WFId)</h5>
<h3>@ViewData["Message"]</h3>
<form asp-action="Modificar">
    <div class="container">
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group col-md-6">
                <label asp-for="Cuit" class="control-label"></label>
                <input asp-for="Cuit" class="form-control" readonly="readonly" />
                <span asp-validation-for="Cuit" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" disabled="disabled" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12">
                <label asp-for="Descr" class="control-label"></label>
                <input asp-for="Descr" class="form-control" />
                <span asp-validation-for="Descr" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12">
                <label asp-for="GTIN" class="control-label"></label>
                <input asp-for="GTIN" class="form-control" />
                <span asp-validation-for="GTIN" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12">
                <label asp-for="UnidadId" class="control-label"></label>
                <select asp-for="UnidadId" class="form-control" asp-items="ViewBag.UnidadId"></select>
                <span asp-validation-for="UnidadId" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12">
                <label asp-for="IndicacionExentoGravadoId" class="control-label"></label>
                <select asp-for="IndicacionExentoGravadoId" class="form-control" asp-items="ViewBag.IndicacionExentoGravadoId"></select>
                <span asp-validation-for="IndicacionExentoGravadoId" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12">
                <label asp-for="AlicuotaIVA" class="control-label"></label>
                <input asp-for="AlicuotaIVA" class="form-control" />
                <span asp-validation-for="AlicuotaIVA" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12">
                <label asp-for="EstadoId" class="control-label">Estado</label>
                <select asp-for="EstadoId" class="form-control" asp-items="ViewBag.EstadoId" disabled="disabled"></select>
                <span asp-validation-for="EstadoId" class="text-danger"></span>
            </div>
            <div class="form-group col-md-12">
                <input type="submit" value="Aceptar" class="btn btn-outline-primary" />
                <a asp-action="Index" asp-controller="Articulo" class="btn btn-outline-primary">Volver</a>
            </div>
        </div>
    </div>
</form>
<div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}